### ISSUE TITLE
Do not process packet twice

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kube-network-policies#10]
1. PodA and PodB in same node is only evaluated once, since it is in forwarding and return will not hit the new Contrack state (I think)
2. PodA in NodeA to PodB in NodeB is evaluated in both Nodes
3. PodA in NodeA to external , is only evaluated once
4. External to PodA in nodeA is only evaluated once

If a network policy was evaluated on origin, don't evaluate again in the destination.
 
/kind feature

**Comment by Rahul-D78** [comment]
Hey aojea, I'm interested to work on this. Any pointers on where to start in the codebase would be greatly appreciated. Thanks!
