### ISSUE TITLE
Enable multiarch builds

### ISSUE THREAD

**Issue by vaskozl** [kubernetes-sigs/kube-network-policies#29]
The current v0.2.0 are not multi-arch and are amd64 specific.

Would be great to be able to run it all around!

**Comment by vaskozl** [comment]
I've now built a multiarch image for [arm64 and armv7](https://github.com/users/vaskozl/packages/container/package/kube-network-policies) and tested it on a cluster. It works wonders so we just need to enable whatever CI to push them out. 

No need to set `GOARCH` in the Dockerfile even.

**Comment by aojea** [comment]
it will be nice to create a script we can call from the makefile https://github.com/kubernetes-sigs/kube-network-policies/blob/081163b898bfe7125dc352499dd0249a7e502337/Makefile#L41-L43

Then I can work in automating it, @vaskozl is this something you want to help?
