### ISSUE TITLE
Use structured logging

### ISSUE THREAD

**Issue by uablrek** [kubernetes-sigs/kube-network-policies#48]
It looks nicer in code and output (if piped through [jq](https://jqlang.github.io/jq/)), and it's much better for post-processing.

This implies a more common-practice use of `context`. A "ctx" should be passed almost everywhere, not a "ctx.Done()".

I think I am almost as big fan of structured logging as @pohly  :smiley:, so I'll be happy to do a PR (but that will be a big one).

/kind feature

**Comment by aojea** [comment]
/assign @uablrek 

please go for it, there is also a dry-run feature @npinaeva is talking about that can make use of this

**Comment by uablrek** [comment]
An informative slack thread with @pohly as ref: https://kubernetes.slack.com/archives/C020CCMUEAX/p1706617958386689

**Comment by uablrek** [comment]
/remove-lifecycle stale

(IMO should issues that have a PR not be stale)
