### ISSUE TITLE
Provide helm chart

### ISSUE THREAD

**Issue by aojea** [kubernetes-sigs/kube-network-policies#98]
I had this feedback that it will be useful to provide a helm chart for users

**Comment by mneverov** [comment]
@aojea Should CRDs be included in the chart?

**Comment by aojea** [comment]
not familiar with the helm ecosystem and its practices, but the CRDs , if included should not be installed by default

**Comment by mneverov** [comment]
implemented in #107, can be closed

**Comment by aojea** [comment]
Thank you very much
